spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: voltex
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        highlight_sql: true
        hbm2ddl:
          import_files: init-data.sql
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  servlet:
    context-path: /